# Общие утилиты
def calculate_token(sentence, model="DEFAULT"):
    # ...

def api_request(req_method, url, headers=None, requester_ip=None, data=None, files=None, stream=False, timeout=None, json=None, **kwargs):
    # ...

def set_response_headers(response):
    # ...

def create_session():
    # ...

def safe_temp_file(prefix, request_id=None):
    # ...

def ERROR_HANDLER(code, model=None, key=None):
    # ...

def handle_options_request():
    # ...

def split_text_for_streaming(text, chunk_size=6):
    # ...
